// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdfeH2pKx9VWQE2Ly2q8PCd91aJgyP8F0',
    appId: '1:736798290875:web:95491d509e99e2cccc4a9e',
    messagingSenderId: '736798290875',
    projectId: 'e-salesperson-75d29',
    authDomain: 'e-salesperson-75d29.firebaseapp.com',
    storageBucket: 'e-salesperson-75d29.appspot.com',
    measurementId: 'G-PQ1RMYV0M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIi6Uvc1A-HzHm3QgCGQ_LZtoaIoXyxDg',
    appId: '1:736798290875:android:c8ff8ca459cf5e09cc4a9e',
    messagingSenderId: '736798290875',
    projectId: 'e-salesperson-75d29',
    storageBucket: 'e-salesperson-75d29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGbCvh02Xqj2-k7Pvo604q8xK6KdAGmJo',
    appId: '1:736798290875:ios:b8871fed718ce240cc4a9e',
    messagingSenderId: '736798290875',
    projectId: 'e-salesperson-75d29',
    storageBucket: 'e-salesperson-75d29.appspot.com',
    iosBundleId: 'com.SVU.AMWS23.eSalesperson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGbCvh02Xqj2-k7Pvo604q8xK6KdAGmJo',
    appId: '1:736798290875:ios:b8871fed718ce240cc4a9e',
    messagingSenderId: '736798290875',
    projectId: 'e-salesperson-75d29',
    storageBucket: 'e-salesperson-75d29.appspot.com',
    iosBundleId: 'com.SVU.AMWS23.eSalesperson',
  );
}
